//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int LookupId { get; set; }
        public string LookupType { get; set; }
        public string LookupName { get; set; }
        public Nullable<int> ParentLookupId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LookupNameImmutable { get; set; }
    }
}
