//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedalDetail
    {
        public int Id { get; set; }
        public Nullable<int> MedalCategoryId { get; set; }
        public string GivenBy { get; set; }
        public string ToWhom { get; set; }
        public string MedalDescription { get; set; }
        public Nullable<System.DateTime> MedalGivenDate { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
