//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACEntry
    {
        public int Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Zone_Id { get; set; }
        public Nullable<int> Range_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<int> PS_Id { get; set; }
        public string ExamineCenterName { get; set; }
        public string Address { get; set; }
        public string FIRNo { get; set; }
        public Nullable<System.DateTime> FIRDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string AccusedName { get; set; }
        public string FIRDetails { get; set; }
        public string FileURL { get; set; }
        public string FileUploadName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PACNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Solver_Name { get; set; }
        public Nullable<int> recruitement_type { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CenterStatus { get; set; }
    }
}
