//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularRecruitment
    {
        public int Id { get; set; }
        public string RecruitmentName { get; set; }
        public Nullable<int> NoOfSeat { get; set; }
        public Nullable<System.DateTime> RecruitmentStartDate { get; set; }
        public Nullable<System.DateTime> RecruitmentEndDate { get; set; }
        public string fileURL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string RecruitmentSubject { get; set; }
    }
}
