//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_Detail
    {
        public int Id { get; set; }
        public string Client_IP_Address { get; set; }
        public Nullable<System.DateTime> Session_Start_Date { get; set; }
        public string Browser_Type { get; set; }
        public string Device_Type { get; set; }
        public string Operating_System { get; set; }
    }
}
